version: "3.9"

services:
  userauth:
    restart: on-failure
    container_name: userauth
    image: userauth-api:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - userauth-network
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${DB_TIMEZONE}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
      - JWT_KEY=${JWT_KEY}
    depends_on:
      - userauthserver
  userauthserver:
    deploy:
      resources:
        reservations:
          memory: 750m
          cpus: "1.5"
    container_name: userauthserver
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    networks:
      - userauth-network
    volumes:
      - userauth-volumes:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

networks:
  userauth-network:
    driver: bridge
    name: userauth-network

volumes:
  userauth-volumes:
    name: userauth-volumes